import store from "./store";
import {
    getProducts,
    getProduct,
    addToCart,
    removeFromCart,
    getShippingAddress,
    getPaymentMethod,
    registerUser,
    loginUser,
    logoutUser,
    getDetails,
    updateDetails,
    createOrder,
    getOrder,
    getOrders,
    payOrder,
} from "./actions";

export {
    store,
    getProducts,
    getProduct,
    addToCart,
    removeFromCart,
    getShippingAddress,
    getPaymentMethod,
    registerUser,
    loginUser,
    logoutUser,
    getDetails,
    updateDetails,
    createOrder,
    getOrder,
    getOrders,
    payOrder,
};