import store from "./store";
import {
    getProducts,
    getProductDetails,
    addToCart,
    removeFromCart,
    getShippingAddress,
    getPaymentMethod,
    registerUser,
    loginUser,
    logoutUser,
    getUserDetails,
    updateDetails,
    getUsers,
    createOrder,
    getOrderDetails,
    getOrders,
    payOrder,
} from "./actions";

export {
    store,
    getProducts,
    getProductDetails,
    addToCart,
    removeFromCart,
    getShippingAddress,
    getPaymentMethod,
    registerUser,
    loginUser,
    logoutUser,
    getUserDetails,
    updateDetails,
    getUsers,
    createOrder,
    getOrderDetails,
    getOrders,
    payOrder,
};