export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const GET_ORDER_LIST_REQUEST = "GET_ORDER_LIST_REQUEST";
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS";
export const GET_ORDER_LIST_ERROR = "GET_ORDER_LIST_ERROR";

export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_ERROR = "GET_ORDER_DETAILS_ERROR";

export const ALL_ORDER_RESET = "ALL_ORDER_RESET";

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_ERROR = "PAY_ORDER_ERROR";

export const GET_ORDER_ALL_REQUEST = "GET_ORDER_ALL_REQUEST";
export const GET_ORDER_ALL_SUCCESS = "GET_ORDER_ALL_SUCCESS";
export const GET_ORDER_ALL_ERROR = "GET_ORDER_ALL_ERROR";

export const DELIVER_ORDER_REQUEST = "DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_ERROR = "DELIVER_ORDER_ERROR";

export const ORDER_RESET = "ORDER_RESET";