export const ORDER_REQUEST = "ORDER_REQUEST";

export const CREATE_ORDER = "CREATE_ORDER";

export const GET_ORDER = "GET_ORDER";

export const GET_ORDERS = "GET_ORDERS";

export const ORDER_ERROR = "ORDER_ERROR";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_ERROR = "ORDER_PAY_ERROR";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";