export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_ERROR = "GET_PRODUCT_DETAILS_ERROR";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const DELETE_PRODUCT_BYID_REQUEST = "DELETE_PRODUCT_BYID_REQUEST";
export const DELETE_PRODUCT_BYID_SUCCESS = "DELETE_PRODUCT_BYID_SUCCESS";
export const DELETE_PRODUCT_BYID_ERROR = "DELETE_PRODUCT_BYID_ERROR";

export const PRODUCT_RESET = "PRODUCT_RESET";

export const REVIEW_PRODUCT_REQUEST = "REVIEW_PRODUCT_REQUEST";
export const REVIEW_PRODUCT_SUCCESS = "REVIEW_PRODUCT_SUCCESS";
export const REVIEW_PRODUCT_ERROR = "REVIEW_PRODUCT_ERROR";
export const REVIEW_PRODUCT_RESET = "REVIEW_PRODUCT_RESET";