export const USER_REQUEST = "USER_REQUEST";
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_DETAILS = "USER_DETAILS";
export const USER_ERROR = "USER_ERROR";
export const UPDATE_ERROR = "UPDATE_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR";

export const DELETE_USER_BYID_REQUEST = "DELETE_USER_BYID_REQUEST";
export const DELETE_USER_BYID_SUCCESS = "DELETE_USER_BYID_SUCCESS";
export const DELETE_USER_BYID_ERROR = "DELETE_USER_BYID_ERROR";

export const GET_USER_BYID_REQUEST = "GET_USER_BYID_REQUEST";
export const GET_USER_BYID_SUCCESS = "GET_USER_BYID_SUCCESS";
export const GET_USER_BYID_ERROR = "GET_USER_BYID_ERROR";

export const UPDATE_USER_BYID_REQUEST = "UPDATE_USER_BYID_REQUEST";
export const UPDATE_USER_BYID_SUCCESS = "UPDATE_USER_BYID_SUCCESS";
export const UPDATE_USER_BYID_ERROR = "UPDATE_USER_BYID_ERROR";

export const USER_RESET = "USER_RESET";